// Generated by Copilot
"use client";

import React, { useEffect, useRef, useState } from "react";
import {
  motion,
  MotionValue,
  useReducedMotion,
  useScroll,
  useTransform,
} from "framer-motion";

type DeviceMode = "phone" | "tablet" | "desktop";

type ContainerScrollProps = {
  titleComponent: string | React.ReactNode;
  children: React.ReactNode;
  className?: string;
  titleClassName?: string;
  cardClassName?: string;
  contentClassName?: string;
  variant?: "default" | "embedded";
};

function getDeviceMode(width: number): DeviceMode {
  if (width <= 640) return "phone";
  if (width <= 1024) return "tablet";
  return "desktop";
}

export const ContainerScroll = ({
  titleComponent,
  children,
  className = "",
  titleClassName = "",
  cardClassName = "",
  contentClassName = "",
  variant = "default",
}: ContainerScrollProps) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const { scrollYProgress } = useScroll({ target: containerRef });
  const [deviceMode, setDeviceMode] = useState<DeviceMode>("desktop");
  const prefersReducedMotion = useReducedMotion();

  useEffect(() => {
    const updateDeviceMode = () => {
      setDeviceMode(getDeviceMode(window.innerWidth));
    };

    updateDeviceMode();
    window.addEventListener("resize", updateDeviceMode);

    return () => {
      window.removeEventListener("resize", updateDeviceMode);
    };
  }, []);

  const scaleDimensions = () => {
    if (deviceMode === "phone") {
      return [0.98, 1];
    }

    if (deviceMode === "tablet") {
      return [0.92, 1];
    }

    return [1.05, 1];
  };

  const rotate = useTransform(
    scrollYProgress,
    [0, 1],
    prefersReducedMotion
      ? [0, 0]
      : deviceMode === "phone"
        ? [0, -8]
        : deviceMode === "tablet"
          ? [0, -14]
          : [0, -18],
  );
  const scale = useTransform(scrollYProgress, [0, 1], prefersReducedMotion ? [1, 1] : scaleDimensions());
  const translate = useTransform(scrollYProgress, [0, 1], prefersReducedMotion ? [0, 0] : [0, -80]);

  const isEmbedded = variant === "embedded";
  const outerHeight = isEmbedded
    ? "h-auto min-h-0"
    : deviceMode === "phone"
      ? "min-h-[48rem]"
      : deviceMode === "tablet"
        ? "min-h-[54rem]"
        : "md:h-[80rem] h-[60rem]";

  const shellPadding = isEmbedded
    ? "p-0"
    : deviceMode === "phone"
      ? "p-2"
      : deviceMode === "tablet"
        ? "p-3 md:p-4"
        : "p-2 md:p-6";

  return (
    <div
      className={`relative flex items-center justify-center overflow-visible ${outerHeight} ${className}`}
      ref={containerRef}
    >
      <div
        className={`relative w-full py-8 md:py-16 ${shellPadding}`}
        style={{ perspective: "1000px" }}
      >
        <Header translate={translate} titleComponent={titleComponent} className={titleClassName} />
        <Card
          rotate={rotate}
          scale={scale}
          deviceMode={deviceMode}
          variant={variant}
          className={cardClassName}
          contentClassName={contentClassName}
        >
          {children}
        </Card>
      </div>
    </div>
  );
};

type HeaderProps = {
  translate: MotionValue<number>;
  titleComponent: string | React.ReactNode;
  className?: string;
};

export const Header = ({ translate, titleComponent, className = "" }: HeaderProps) => {
  return (
    <motion.div
      style={{ translateY: translate }}
      className={`mx-auto max-w-5xl text-center ${className}`}
    >
      {titleComponent}
    </motion.div>
  );
};

type CardProps = {
  rotate: MotionValue<number>;
  scale: MotionValue<number>;
  children: React.ReactNode;
  deviceMode: DeviceMode;
  variant: "default" | "embedded";
  className?: string;
  contentClassName?: string;
};

export const Card = ({
  rotate,
  scale,
  children,
  deviceMode,
  variant,
  className = "",
  contentClassName = "",
}: CardProps) => {
  const shellHeight =
    variant === "embedded"
      ? "h-auto min-h-0"
      : deviceMode === "phone"
        ? "min-h-[30rem]"
        : deviceMode === "tablet"
          ? "min-h-[34rem]"
          : "h-[40rem] md:h-[44rem]";

  const shellRadius = variant === "embedded" ? "rounded-[20px]" : deviceMode === "phone" ? "rounded-[24px]" : "rounded-[30px]";
  const shellBorder = variant === "embedded" ? "border" : deviceMode === "phone" ? "border-2" : "border-4";
  const shellInnerPadding =
    variant === "embedded"
      ? "p-4 md:p-5"
      : deviceMode === "phone"
        ? "p-2"
        : deviceMode === "tablet"
          ? "p-3"
          : "p-2 md:p-6";

  return (
    <motion.div
      style={{
        rotateX: rotate,
        scale,
        boxShadow:
          variant === "embedded"
            ? "0 18px 46px rgba(14, 17, 16, 0.14)"
            : "0 0 #0000004d, 0 9px 20px #0000004a, 0 37px 37px #00000042, 0 84px 50px #00000026, 0 149px 60px #0000000a, 0 233px 65px #00000003",
      }}
      className={`relative mx-auto ${variant === "embedded" ? "mt-0 max-w-[1120px]" : "mt-6 max-w-5xl"} w-full bg-[#222222] ${shellHeight} ${shellRadius} ${shellBorder} border-[#6C6C6C] ${variant === "embedded" ? "shadow-[0_18px_46px_rgba(14,17,16,0.14)]" : "shadow-2xl"} ${shellInnerPadding} ${className}`}
    >
      <div
        className={`h-full w-full overflow-hidden rounded-2xl bg-gray-100 dark:bg-zinc-900 ${contentClassName}`}
      >
        {children}
      </div>
    </motion.div>
  );
};
